### ISSUE TITLE
entropy-0.4 fails to build with GHC-7.8 and older

### ISSUE THREAD

**Issue by phadej** [TomMD/entropy#36]

**Comment by TomMD** [comment]
You use 7.8 still?  I felt supporting 3 versions should suffice. Hurm.

**Comment by hvr** [comment]
@TomMD It's totally fine if you don't want to support pre-AMP GHCs! The problem is rather, that the package advertises to work with `base >= 4.3` and thus allows the cabal solver to pick `entropy-0.4` with GHC 7.8 and older... and this showed up on https://matrix.hackage.haskell.org/package/entropy:


```
In order, the following will be built (use -v for more details):
 - entropy-0.4 {entropy-0.4-inplace} (lib:entropy) (first run)
[1 of 1] Compiling Main             ( /tmp/matrix-worker/1514748391/dist-newstyle/build/x86_64-linux/ghc-7.8.4/entropy-0.4/setup/setup.hs, /tmp/matrix-worker/1514748391/dist-newstyle/build/x86_64-linux/ghc-7.8.4/entropy-0.4/setup/Main.o )
Linking /tmp/matrix-worker/1514748391/dist-newstyle/build/x86_64-linux/ghc-7.8.4/entropy-0.4/setup/setup ...
Configuring entropy-0.4...
Result of RDRAND Test: True
Preprocessing library for entropy-0.4..
Building library for entropy-0.4..
[1 of 2] Compiling System.EntropyNix ( System/EntropyNix.hs, /tmp/matrix-worker/1514748391/dist-newstyle/build/x86_64-linux/ghc-7.8.4/entropy-0.4/build/System/EntropyNix.o )

System/EntropyNix.hs:54:16: Not in scope: ‘<$>’

System/EntropyNix.hs:57:11: Not in scope: ‘pure’
```

Anyway, I just fixed up the lower bound on `base` to reflect reality at https://hackage.haskell.org/package/entropy-0.4/revisions/ 

So there's no need to upload a new release if you don't intend to restore support for GHC < 7.10; just fixup `entropy.cabal` in Git in the same way. If, however, you want to restore pre-AMP support, lemme know and I'll gladly provide you a PR.

**Comment by TomMD** [comment]
Thanks @hvr. @phadej  Are you satisfied or are you hoping for support for old GHCs?  Honestly, I'm not keen on it but would accept a clean patch.

**Comment by phadej** [comment]
IMHO, as the package anyways uses CPP, restoring support isn't big task. Also updating Travis-CI to test "supported" GHCs will prevent similar issues in the future (hvr's multi-ghc-travis scripts).
