### ISSUE TITLE
Fails to compile with GHC 7.0.4 and GHC 7.2.2

### ISSUE THREAD

**Issue by hvr** [TomMD/entropy#23]
This is quite a problem since `entropy` by being so popular is contained in quite a few build-dependencies, and running into a compile failure breaks the cabal solver by not allowing it to backtrack to other versions.

If support for GHC 7.0/7.2 is effectively terminated, please add a `base >= 4.5` constraint to future releases, so the cabal solver at least knows it should try something else.

**Comment by TomMD** [comment]
I have edited the package information for versions >= 3.4 to set base >= 4.5.  Feel free to re-open if this didn't go far enough.

**Comment by hvr** [comment]
I'm afraid it's not enough, as `cabal install entropy` would now pick the latest admissible version which is currently `entropy-0.3.3` which fails to build, see https://ghc.haskell.org/~hvr/buildreports/entropy.html

**Comment by TomMD** [comment]
Since you have GHC <=7.2 setup and motivation perhaps you could create a pull request or add info about which parts of base that are used that aren't in whatever comes with 7.0.x?

**Comment by hvr** [comment]
The problem is it fails already during the `configure` step:

```
 /tmp/entropy-0.3.3-11688/entropy-0.3.3/dist/dist-sandbox-4f4ef211/setup/setup.hs:47:15:
     Not in scope: `rawSystemExitCode'
     Perhaps you meant `rawSystemExit' (imported from Distribution.Simple.Utils)
 cabal: Error: some packages failed to install:
 entropy-0.3.3 failed during the configure step. The exception was:
 ExitFailure 1
```

A non-perfect but surely handling 99% of GHC<=7.2 cases would be to simply assume that  the `Cabal` version correlates with the `__GLASGOW_HASKELL__` value...

Alternatively, one could upload two releases, one for `base>=4.5` and one for `base<4.5` and avoid any CPP in `Setup.hs`. 

For the long-term future, @dcoutts is, afaik, working on allowing to specify the `Cabal` version a `Setup.hs` is compatible with in the `.cabal` file... but that doesn't help us here yet.

**Comment by hvr** [comment]
I think I've found a way that should even work for cases where GHC 7.0 users have installed a newer Cabal version... PR coming soon

**Comment by hvr** [comment]
Thanks! Much better: https://ghc.haskell.org/~hvr/buildreports/entropy.html

PS: Just to give you some numbers how many failures were caused by `entropy-3.3.*` failing to configure for that small package-set I had (the first number in each line is the number of build-jobs failed due to entropy failing to build):

```
     32 certificate.log:STDERR: entropy-0.3.3 failed during the configure step.
      2 cipher-aes.log:STDERR: entropy-0.3.3 failed during the configure step.
     54 cryptocipher.log:STDERR: entropy-0.3.3 failed during the configure step.
     42 cryptohash.log:STDERR: entropy-0.3.4.1 failed during the configure step.
      8 crypto-numbers.log:STDERR: entropy-0.3.3 failed during the configure step.
     10 crypto-pubkey.log:STDERR: entropy-0.3.3 failed during the configure step.
      8 pureMD5.log:STDERR: entropy-0.3.4.1 failed during the configure step.
     34 RSA.log:STDERR: entropy-0.3.3 failed during the configure step.
     96 tls.log:STDERR: entropy-0.3.3 failed during the configure step.
```
